### ISSUE TITLE
composer.json update

### ISSUE THREAD

**Issue by pressi** [felixpfeiffer/contao-simple-event-registration#12]
Hallo!

In der Composer Datei sollte folgendes geändert werden da sonst die Erweiterung nicht installiert werden kann, z.B.: in Contao 3.4.5:

von:
"contao-community-alliance/composer-installer":"~2.0"

in:
"contao-community-alliance/composer-plugin":"~2.0"

Hier ein Forum Beitrag:
https://community.contao.org/de/showthread.php?56545-Composer-blockiert-Updates-installation-von-Modulen-wegen-einer-Erweiterung

Lg

**Comment by felixpfeiffer** [comment]
Ist behoben. Danke für den Hinweis.
